version: "3"
services:
 tim:
  depends_on:
   - ts-watcher
 nginx:
  ports:
   - "${NGINX_PORT}:80"
 ts-watcher:
  image: timimages/tim:${TIM_IMAGE_TAG}
  volumes:
   - .:/service
   - /opt/jspm_cache:/root/.jspm
  working_dir: /service/timApp/static/scripts
  command: jspm bundle tim/main - "(tim/main - [tim/**/*])" build/tim.js -wm
  restart: unless-stopped
 pali:
  environment:
    SHOW_TEMPLATES: "False"