version: "3"
services:
 tim:
  depends_on:
   - postgresql-test
   - chrome
  tmpfs:
   - /tmp
  command: "sleep infinity"
 postgresql:
  command: "sleep infinity"
 postgresql-test:
  image: postgres:11
  tmpfs:
   - /var/lib/postgresql/data
 chrome:
  image: selenium/standalone-chrome:3.141.59-uranium
  tmpfs:
   - /tmp
   - /home/seluser
 nginx:
  image: timimages/local_nginx_dev:compose
  build:
   args:
    MAIN_CONFIG: tim_dev.conf
 tests:
  image: timimages/tim:${TIM_IMAGE_TAG}
  command: "python3 -m unittest ${TEST_PARAMS:-discover tests/ 'test_*.py' .}"
  volumes:
   - .:/service:ro
   - ./screenshots:/service/screenshots:rw
   - ./timApp/static/generated:/service/timApp/static/generated:rw
   - ./timApp/static/.webassets-cache:/service/timApp/static/.webassets-cache:rw
   - ./timApp/static/scripts:/service/timApp/static/scripts:rw
  environment:
   TIM_SETTINGS: testconfig.py
   PYTHONPATH: /service:/service/timApp/modules/py
   GITLAB_CI: ${GITLAB_CI:-false}
  depends_on:
   - nginx
  tmpfs:
   - /tmp/doctest_files
  working_dir: /service/timApp
