version: "3.7"
x-mailman-common-env:
 &mailman-common-env
  DATABASE_TYPE: sqlite
  DATABASE_URL: sqlite:////opt/mailmandb/mailmanweb.db
  DATABASE_CLASS: mailman.database.sqlite.SQLiteDatabase
  HYPERKITTY_API_KEY: test

services:
  mailman-core:
    image: timimages/mailman-core:latest
    restart: unless-stopped
    profiles:
      - dev
    volumes:
      - ./mailman/db:/opt/mailmandb
      - ./mailman/core:/opt/mailman
    environment:
      <<: *mailman-common-env
      HYPERKITTY_URL: http://mailman-web:8000/mailman3/hyperkitty/
      INIT_DEV: 1
  mailman-web:
    image: timimages/mailman-web:latest
    restart: unless-stopped
    profiles:
      - dev
    depends_on:
      - mailman-core
    volumes:
      - ./mailman/db:/opt/mailmandb
      - ./mailman/web:/opt/mailman-web-data
      - ./mailman/messages:/tmp/mailman-messages
    environment:
      <<: *mailman-common-env
      SECRET_KEY: test
      MAILMAN_ADMIN_USER: admin
      MAILMAN_ADMIN_EMAIL: admin@example.com
      SERVE_FROM_DOMAIN: localhost
      URL_BASE_DIR: mailman3
  caddy:
    volumes:
      - ${CADDY_MAILMAN_STATIC_DIR:-}:/var/www/mailman3/static